-- MySQL Script generated by MySQL Workbench
-- Sun Apr 19 14:44:17 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema SanluisDB
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema SanluisDB
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `SanluisDB` DEFAULT CHARACTER SET utf8 ;
USE `SanluisDB` ;

-- -----------------------------------------------------
-- Table `SanluisDB`.`Roles`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SanluisDB`.`Roles` (
  `idRol` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NULL,
  PRIMARY KEY (`idRol`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SanluisDB`.`Centro`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SanluisDB`.`Centro` (
  `idCentro` INT NOT NULL AUTO_INCREMENT,
  `nombre_centro` VARCHAR(45) NULL,
  `ciudad_centro` VARCHAR(45) NULL,
  PRIMARY KEY (`idCentro`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SanluisDB`.`Aulas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SanluisDB`.`Aulas` (
  `idAulas` INT NOT NULL AUTO_INCREMENT,
  `Centro_idCentro` INT NOT NULL,
  `rangoIps` VARCHAR(45) NULL,
  `nombre` VARCHAR(45) NULL,
  `descripcion` VARCHAR(45) NULL,
  `capacidad` INT NULL,
  PRIMARY KEY (`idAulas`),
  INDEX `fk_Aulas_Centro1_idx` (`Centro_idCentro` ASC) VISIBLE,
  UNIQUE INDEX `nombre_UNIQUE` (`nombre` ASC) VISIBLE,
  CONSTRAINT `fk_Aulas_Centro1`
    FOREIGN KEY (`Centro_idCentro`)
    REFERENCES `SanluisDB`.`Centro` (`idCentro`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SanluisDB`.`Stock`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SanluisDB`.`Stock` (
  `idStock` INT NOT NULL AUTO_INCREMENT,
  `unidadesStock` INT NULL,
  `limiteInferior` INT NULL,
  `descripcion` VARCHAR(45) NULL,
  PRIMARY KEY (`idStock`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SanluisDB`.`Equipos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SanluisDB`.`Equipos` (
  `idEquipos` INT NOT NULL AUTO_INCREMENT,
  `Aulas_idAulas` INT NULL,
  `nombre` VARCHAR(45) NULL,
  `discoDuro` INT NULL,
  `ram` INT NULL,
  `ipEquipo` VARCHAR(45) NULL,
  `Stock_idStock` INT NULL,
  PRIMARY KEY (`idEquipos`),
  INDEX `fk_Equipos_Aulas1_idx` (`Aulas_idAulas` ASC) VISIBLE,
  INDEX `fk_Equipos_Stock1_idx` (`Stock_idStock` ASC) VISIBLE,
  CONSTRAINT `fk_Equipos_Aulas1`
    FOREIGN KEY (`Aulas_idAulas`)
    REFERENCES `SanluisDB`.`Aulas` (`idAulas`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Equipos_Stock1`
    FOREIGN KEY (`Stock_idStock`)
    REFERENCES `SanluisDB`.`Stock` (`idStock`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SanluisDB`.`Componentes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SanluisDB`.`Componentes` (
  `idComponentes` INT NOT NULL AUTO_INCREMENT,
  `Equipos_idEquipos` INT NULL,
  `Stock_idStock` INT NULL,
  `descripcion` VARCHAR(45) NULL,
  `tipo` VARCHAR(45) NULL,
  `codLicencia` VARCHAR(45) NULL,
  `tipoHardware` VARCHAR(45) NULL,
  `marca` VARCHAR(45) NULL,
  `peso` DOUBLE NULL,
  PRIMARY KEY (`idComponentes`),
  INDEX `fk_Componentes_Equipos1_idx` (`Equipos_idEquipos` ASC) VISIBLE,
  INDEX `fk_Componentes_Stock1_idx` (`Stock_idStock` ASC) VISIBLE,
  CONSTRAINT `fk_Componentes_Equipos1`
    FOREIGN KEY (`Equipos_idEquipos`)
    REFERENCES `SanluisDB`.`Equipos` (`idEquipos`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Componentes_Stock1`
    FOREIGN KEY (`Stock_idStock`)
    REFERENCES `SanluisDB`.`Stock` (`idStock`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SanluisDB`.`Usuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SanluisDB`.`Usuarios` (
  `idUsuarios` VARCHAR(45) NOT NULL,
  `Roles_idRol` INT NOT NULL,
  `Equipos_idEquipos` INT NULL,
  `userName` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `pass` VARCHAR(256) NOT NULL,
  `direccion` VARCHAR(45) NULL,
  `telefono` VARCHAR(45) NULL,
  `nombre` VARCHAR(45) NULL,
  `apellidos` VARCHAR(45) NULL,
  PRIMARY KEY (`idUsuarios`),
  INDEX `fk_Usuarios_Roles_idx` (`Roles_idRol` ASC) VISIBLE,
  INDEX `fk_Usuarios_Equipos1_idx` (`Equipos_idEquipos` ASC) VISIBLE,
  CONSTRAINT `fk_Usuarios_Roles`
    FOREIGN KEY (`Roles_idRol`)
    REFERENCES `SanluisDB`.`Roles` (`idRol`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Usuarios_Equipos1`
    FOREIGN KEY (`Equipos_idEquipos`)
    REFERENCES `SanluisDB`.`Equipos` (`idEquipos`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SanluisDB`.`Proveedores`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SanluisDB`.`Proveedores` (
  `idProveedores` INT NOT NULL AUTO_INCREMENT,
  `cif` VARCHAR(45) NULL,
  `nombre` VARCHAR(45) NULL,
  `email` VARCHAR(45) NULL,
  `direccion` VARCHAR(45) NULL,
  `telef` VARCHAR(45) NULL,
  PRIMARY KEY (`idProveedores`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SanluisDB`.`SolInci`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SanluisDB`.`SolInci` (
  `idSolInci` INT NOT NULL AUTO_INCREMENT,
  `Realizada` VARCHAR(45) NOT NULL,
  `Asignada` VARCHAR(45) NULL,
  `Equipos_idEquipos` INT NOT NULL,
  `tipo` VARCHAR(45) NULL,
  `fechaSol` DATETIME NULL,
  `fechaFin` DATETIME NULL,
  `estado` VARCHAR(45) NULL,
  `descripcion` VARCHAR(45) NULL,
  `prioridad` INT NULL,
  `Componentes_idComponentes` INT NULL,
  PRIMARY KEY (`idSolInci`),
  INDEX `fk_SolInci_Usuarios1_idx` (`Realizada` ASC) VISIBLE,
  INDEX `fk_SolInci_Usuarios2_idx` (`Asignada` ASC) VISIBLE,
  INDEX `fk_SolInci_Equipos1_idx` (`Equipos_idEquipos` ASC) VISIBLE,
  INDEX `fk_SolInci_Componentes1_idx` (`Componentes_idComponentes` ASC) VISIBLE,
  CONSTRAINT `fk_SolInci_Usuarios1`
    FOREIGN KEY (`Realizada`)
    REFERENCES `SanluisDB`.`Usuarios` (`idUsuarios`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_SolInci_Usuarios2`
    FOREIGN KEY (`Asignada`)
    REFERENCES `SanluisDB`.`Usuarios` (`idUsuarios`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_SolInci_Equipos1`
    FOREIGN KEY (`Equipos_idEquipos`)
    REFERENCES `SanluisDB`.`Equipos` (`idEquipos`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_SolInci_Componentes1`
    FOREIGN KEY (`Componentes_idComponentes`)
    REFERENCES `SanluisDB`.`Componentes` (`idComponentes`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SanluisDB`.`Usuarios_has_Aulas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SanluisDB`.`Usuarios_has_Aulas` (
  `Usuarios_idUsuarios` VARCHAR(45) NOT NULL,
  `Aulas_idAulas` INT NOT NULL,
  PRIMARY KEY (`Usuarios_idUsuarios`, `Aulas_idAulas`),
  INDEX `fk_Usuarios_has_Aulas_Aulas1_idx` (`Aulas_idAulas` ASC) VISIBLE,
  INDEX `fk_Usuarios_has_Aulas_Usuarios1_idx` (`Usuarios_idUsuarios` ASC) VISIBLE,
  CONSTRAINT `fk_Usuarios_has_Aulas_Usuarios1`
    FOREIGN KEY (`Usuarios_idUsuarios`)
    REFERENCES `SanluisDB`.`Usuarios` (`idUsuarios`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Usuarios_has_Aulas_Aulas1`
    FOREIGN KEY (`Aulas_idAulas`)
    REFERENCES `SanluisDB`.`Aulas` (`idAulas`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SanluisDB`.`compras`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SanluisDB`.`compras` (
  `idcompras` INT NOT NULL AUTO_INCREMENT,
  `Proveedores_idProveedores` INT NOT NULL,
  `fechaCompra` DATETIME NULL,
  PRIMARY KEY (`idcompras`),
  INDEX `fk_compras_Proveedores1_idx` (`Proveedores_idProveedores` ASC) VISIBLE,
  CONSTRAINT `fk_compras_Proveedores1`
    FOREIGN KEY (`Proveedores_idProveedores`)
    REFERENCES `SanluisDB`.`Proveedores` (`idProveedores`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SanluisDB`.`Historico_Compras`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SanluisDB`.`Historico_Compras` (
  `Stock_idStock` INT NOT NULL,
  `compras_idcompras` INT NOT NULL,
  `unidades` INT NULL,
  PRIMARY KEY (`Stock_idStock`, `compras_idcompras`),
  INDEX `fk_Stock_has_compras_compras1_idx` (`compras_idcompras` ASC) VISIBLE,
  INDEX `fk_Stock_has_compras_Stock1_idx` (`Stock_idStock` ASC) VISIBLE,
  CONSTRAINT `fk_Stock_has_compras_Stock1`
    FOREIGN KEY (`Stock_idStock`)
    REFERENCES `SanluisDB`.`Stock` (`idStock`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Stock_has_compras_compras1`
    FOREIGN KEY (`compras_idcompras`)
    REFERENCES `SanluisDB`.`compras` (`idcompras`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
